component-ids: [introduction, chart, series, indicator, scale, svg, annotation, tool, layout, util, data, samplers]

components:
  introduction:
    name: Introduction
  annotation:
    name: Annotations
  chart:
    name: Chart
  series:
    name: Series
  indicator:
    name: Indicators
  scale:
    name: Scale
  tool:
    name: Tools
  svg:
    name: SVG
  layout:
    name: Layout
  util:
    name: Util
  data:
    name: Data
  samplers:
    name: Samplers

example-ids: [examples]

examples:
  examples:
    name: Examples
